In [25]:
# Load the data and libraries
import pandas as pd
import numpy as np
import random
from scipy import stats
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')

# payroll = pd.read_json('https://data.cityofnewyork.us/resource/k397-673e.json')
payroll = pd.read_csv('./Citywide_Payroll_Data__Fiscal_Year_2020.csv', low_memory=False)

In [26]:
def laplace_mech(v, sensitivity, epsilon):
    return v + np.random.laplace(loc=0, scale=sensitivity / epsilon)

def laplace_mech_vec(vec, sensitivity, epsilon):
    return [v + np.random.laplace(loc=0, scale=sensitivity / epsilon) for v in vec]

def gaussian_mech(v, sensitivity, epsilon, delta):
    return v + np.random.normal(loc=0, scale=sensitivity * np.sqrt(2*np.log(1.25/delta)) / epsilon)

def gaussian_mech_vec(vec, sensitivity, epsilon, delta):
    return [v + np.random.normal(loc=0, scale=sensitivity * np.sqrt(2*np.log(1.25/delta)) / epsilon)
            for v in vec]

def pct_error(orig, priv):
    return np.abs(orig - priv)/orig * 100.0

In [32]:
payroll.columns.values.tolist()

['Fiscal Year',
 'Payroll Number',
 'Agency Name',
 'Last Name',
 'First Name',
 'Mid Init',
 'Agency Start Date',
 'Work Location Borough',
 'Title Description',
 'Leave Status as of June 30',
 'Base Salary',
 'Pay Basis',
 'Regular Hours',
 'Regular Gross Paid',
 'OT Hours',
 'Total OT Paid',
 'Total Other Pay']

In [29]:
payroll

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay
0,2020,2.0,OFFICE OF THE MAYOR,FULEIHAN,DEAN,A,12/31/2017,MANHATTAN,FIRST DEPUTY MAYOR,ACTIVE,291139.0,per Annum,1820.0,286715.07,0.0,0.00,0.00
1,2020,2.0,OFFICE OF THE MAYOR,DE BLASIO,BILL,NaN,01/01/2014,MANHATTAN,MAYOR,ACTIVE,258750.0,per Annum,1820.0,257351.53,0.0,0.00,1500.00
2,2020,2.0,OFFICE OF THE MAYOR,ANGLIN,LAURA,L,01/03/2017,MANHATTAN,DEPUTY MAYOR,ACTIVE,251982.0,per Annum,1820.0,248153.39,0.0,0.00,0.00
3,2020,2.0,OFFICE OF THE MAYOR,THOMPSON,JAMES,P,03/12/2018,MANHATTAN,DEPUTY MAYOR,ACTIVE,251982.0,per Annum,1820.0,248153.39,0.0,0.00,0.00
4,2020,2.0,OFFICE OF THE MAYOR,BEEN,VICKI,L,02/07/2017,MANHATTAN,DEPUTY MAYOR,ACTIVE,251982.0,per Annum,1820.0,243097.64,0.0,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590205,2020,996.0,NYC HOUSING AUTHORITY,HOLLOWAY,REESHA,Y,04/18/2019,MANHATTAN,CITY SEASONAL AIDE,CEASED,27375.0,Prorated Annual,-63.0,-607.41,0.0,0.00,-1020.00
590206,2020,996.0,NYC HOUSING AUTHORITY,WATKINS,CHRISTOPHER,T,05/14/2012,BRONX,CARETAKER,CEASED,43941.0,per Annum,-80.0,-3370.82,0.0,0.00,1626.15
590207,2020,996.0,NYC HOUSING AUTHORITY,GREEN,DANIELLE,E,05/14/2012,QUEENS,CARETAKER,CEASED,43941.0,per Annum,-80.0,-1685.41,-5.0,-184.14,0.00
590208,2020,996.0,NYC HOUSING AUTHORITY,SCOTT,PRECIOUS,NaN,03/25/2019,BROOKLYN,CARETAKER,CEASED,31286.0,per Annum,-160.0,-2400.02,0.0,0.00,0.00
590209,2020,996.0,NYC HOUSING AUTHORITY,ISAACS,EUNIQUE,NaN,05/08/2017,BROOKLYN,CARETAKER,CEASED,37434.0,per Annum,-96.0,2898.08,0.0,0.00,-9044.19

In [41]:
query = len(payroll[payroll['Agency Name'] == 'OFFICE OF THE MAYOR'])
laplace_mech(query, 1, 1)

800.2939025558536